# Generated by Django 5.2.7 on 2025-10-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMserv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='middle_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
