# Generated by Django 5.2.8 on 2025-11-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMserv', '0002_alter_client_middle_name_alter_employee_middle_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='uploads/photos/')),
                ('document', models.FileField(upload_to='uploads/documents/')),
            ],
        ),
    ]
