# Generated by Django 5.2.8 on 2025-11-25 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMserv', '0004_delete_yourmodel_client_photo_device_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=25, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=25, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='client',
            name='middle_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='clients/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='part_name',
            field=models.CharField(max_length=100, verbose_name='Деталь'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='part_source',
            field=models.CharField(max_length=50, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='supplier',
            field=models.CharField(max_length=100, verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='device',
            name='appearance',
            field=models.TextField(verbose_name='Внешний вид'),
        ),
        migrations.AlterField(
            model_name='device',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.CharField(max_length=50, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='device',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='devices/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(max_length=50, verbose_name='Серийник'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='access_type',
            field=models.CharField(max_length=20, verbose_name='Доступ'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=25, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=25, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('master', 'Мастер'), ('cashier', 'Кассир'), ('admin', 'Администратор')], max_length=50, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_cashier', to='SAMserv.employee', verbose_name='Кассир'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAMserv.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAMserv.device', verbose_name='Устройство'),
        ),
        migrations.AlterField(
            model_name='order',
            name='diagnosis',
            field=models.TextField(blank=True, verbose_name='Диагностика'),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Предварительная цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Итоговая цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='issue_description',
            field=models.TextField(verbose_name='Проблема'),
        ),
        migrations.AlterField(
            model_name='order',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_master', to='SAMserv.employee', verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('diagnostics', 'Диагностика'), ('repair', 'В ремонте'), ('ready', 'Готов'), ('issued', 'Выдан')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('qr', 'QR-код')], max_length=10, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(max_length=100, verbose_name='Услуга'),
        ),
    ]
