"""
Django settings for proekSERV project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/  

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/  
"""
# settings.py/proekSERV

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/  

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k94phhs5-#8et!#t$)*z%qs9u0cd5^0!ugy!h-&(%f$1=x8t4b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'SAMserv',
    'corsheaders',
    'rest_framework', 
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = 'proekSERV.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'proekSERV.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases  

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
#   https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators  

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
#   https://docs.djangoproject.com/en/5.2/topics/i18n/  

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/  

# Указываем URL, по которому будут доступны статические файлы
STATIC_URL = '/static/'

# Определяем директории, где Django будет искать статические файлы в режиме разработки
STATICFILES_DIRS = [
    BASE_DIR / "static",  #  папка
]

# Указываем директорию, куда будет собираться вся статика для продакшена
STATIC_ROOT = BASE_DIR / "staticfiles"  # Это папка, куда попадут файлы после collectstatic

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field  

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Путь к директории, где будут храниться загруженные пользователем файлы (фото, документы и т.д.)
MEDIA_ROOT = BASE_DIR / "media"  # Например, создаст папку 'media' в корне проекта

# URL, по которому будут доступны эти файлы в браузере
MEDIA_URL = "/media/"

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]